//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knihovna_SAN.Client {
    
    
    public partial class TestPage {
        protected global::System.Web.UI.WebControls.TextBox TextBox_categoryName;
        protected global::System.Web.UI.WebControls.TextBox TextBox_categoryType;
        protected global::System.Web.UI.WebControls.Button Button1;
        protected global::System.Web.UI.WebControls.TextBox TextBox_actionDate;
        protected global::System.Web.UI.WebControls.TextBox TextBox_actionCapacity;
        protected global::System.Web.UI.WebControls.Button Button2;
        protected global::System.Web.UI.WebControls.TextBox TextBox_actionName;
        protected global::System.Web.UI.WebControls.TextBox TextBox_actionCost;

    }
}
